### ISSUE TITLE
Add NUnit format support

### ISSUE THREAD

**Issue by EOssesFrazoni** [test-results-reporter/parser#4]
Is it possible for this project to support NUnit .xml result files as input?

**Comment by ASaiAnudeep** [comment]
Currently it is not supported. But I'm marking this issue as an enhancement. Feel free to raise a pull request to support the result type. 

Or, please provide us some sample result files from NUnit.

**Comment by EOssesFrazoni** [comment]
[testresult_30.txt](https://github.com/test-results-reporter/parser/files/8523034/testresult_30.txt)
Hi, thanks for your reply.  It would be a very difficult task for me to develop this.

I've attached a sample XML file (had to change extension to .txt to upload it here). It is taken from this web, where more information about this file is detailed:
 https://docs.nunit.org/articles/nunit/technical-notes/usage/XML-Formats.html

Thanks again.
Have a nice morning.
