### ISSUE TITLE
revisit tags and meta data

### ISSUE THREAD

**Issue by ASaiAnudeep** [test-results-reporter/parser#72]
- Tags can be separate property
- Metadata can be a separate property

**Comment by bryanbcook** [comment]
Can you elaborate on what you'd like to do here?

**Comment by ASaiAnudeep** [comment]
Break tags into its own property

```ts
declare class TestCase {
  name: string;
  total: number;
  
  tags: string[]
  meta_data: Map<string,string>;
  
}
```

I have assigned this myself.
